id = "revofmt-lsp"
name = "Revo Formatter LSP"
version = "0.2.1"
schema_version = 1
authors = ["Idan Gilboa"]
description = "Formats unsaved Revo buffers using the installed revofmt CLI"
repository = "https://github.com/w0x7y/revofmt-zed"

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.revofmt-lsp]
name = "Revo Formatter LSP"
languages = ["Revo"]
language_ids = { Revo = "revo" }
