// Generated by scripts/package-server --update-checksums.
pub const SERVER_FILES: &[(&str, &str)] = &[
    (
        "server/documents.cjs",
        "b57dc6a9ad47e719ee76a2be237b0660e97a8e6a22e8473073c81838451c9ff6",
    ),
    (
        "server/formatter.cjs",
        "3be2bb0db20427082f62909f0452a467dd4af3e0ba9fe8bc5b3108f63c79561c",
    ),
    (
        "server/main.cjs",
        "c56c2090e2cf89a5cb17c1dcb3059448ec17e9f20fc479ee6a5359e57516a2f3",
    ),
    (
        "server/protocol.cjs",
        "151b77781e24b8c68dbafeb362460cb78a381bda65de5d2f4d3f45a723a63a0b",
    ),
];
