// Generated by scripts/package-server --update-checksums.
pub const SERVER_FILES: &[(&str, &str)] = &[
    (
        "server/documents.cjs",
        "b57dc6a9ad47e719ee76a2be237b0660e97a8e6a22e8473073c81838451c9ff6",
    ),
    (
        "server/formatter.cjs",
        "fd49c3db83a301ad35ce1b5b6bdc71dc69938509a026346347550dbb6f177269",
    ),
    (
        "server/main.cjs",
        "8758eb716e26ded8a79e4335a2dc80581012a13c9aef901170a1ae69e031ccdc",
    ),
    (
        "server/protocol.cjs",
        "151b77781e24b8c68dbafeb362460cb78a381bda65de5d2f4d3f45a723a63a0b",
    ),
];
